spring:
  application:
    name: scheduling-backend
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      dialect:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/SchedulingDb
    username: root
    password: "1234"
    hikari:
      idle-timeout: 10000
  mail:
    host: smtp.gmail.com
    port: 587
    username: burak.b.gunden@gmail.com
    password:

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    context-path: /scheduling

  port: 8081
security:
  jwt:
    token:
      ssecret-key: secret-key-for-encryption
      expiration: 600000
