spring:
  application:
    name: scheduling-backend
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/SchedulingDb
    username: root
    password: 1234
    hikari:
      idle-timeout: 10000

server:
  servlet:
    context-path: /scheduling

  port: 8081
security:
  jwt:
    token:
      ssecret-key: secret-key-for-encryption
      expiration: 600000